apiVersion: v1
kind: ConfigMap
metadata:
  name: example-config
  namespace: default
data:
  # Example key
  example_key: "example_value"

  # MongoDB
  MONGO_USERNAME: "mongoadmin"
  MONGO_PASSWORD: "mongopassword"
  MONGO_INITDB_ROOT_USERNAME: "mongoadmin"
  MONGO_INITDB_ROOT_PASSWORD: "mongopassword"
  ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
  ME_CONFIG_MONGODB_AUTH_USERNAME: "mongoadmin"
  ME_CONFIG_MONGODB_AUTH_PASSWORD: "mongopassword"
  ME_CONFIG_MONGODB_URL: mongodb://mongoadmin:mongopassword@mongodb:27017
  ME_CONFIG_BASICAUTH_USERNAME: "mongoadmin"
  ME_CONFIG_BASICAUTH_PASSWORD: "mongopassword"
  ME_CONFIG_MONGODB_SERVER: "mongodb-0.mongodb.default.svc.cluster.local"
  mongo_db_url: mongodb://mongoadmin:mongopassword@mongodb:27017
  mongo_database_name: "data_base"
  collection_name: "collection_name"

  # RabbitMQ
  RABBITMQ_USER: "rabbitmq"
  RABBITMQ_PASS: "password123"
  RABBITMQ_DEFAULT_USER: "rabbitmq"
  RABBITMQ_DEFAULT_PASS: "password123"
  message_broker_url: amqp://rabbitmq:password123@rabbitmq:5672/
  default_queue_name: "queue1"